sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
script:
script:
  - (cd evaluation_script && python -m unittest -v conll17_ud_eval)
  - (cd evaluation_script && python conll17_ud_eval.py -v -w weights.cnc-like tests/gold.conllu tests/sys1.conllu | diff -s tests/sys1-expected.results -)
  - (cd evaluation_script && python conll17_ud_eval.py -v -w weights.cnc-like tests/gold.conllu tests/sys2.conllu | diff -s tests/sys2-expected.results -)
